#!/bin/bash
# Create a systemd service that autostarts & manages a docker-compose instance in the current directory
# by Uli Köhler - https://techoverflow.net
# Licensed as CC0 1.0 Universal
SERVICENAME=$(basename $(pwd))

echo "Creating systemd service... /etc/systemd/system/${SERVICENAME}.service"

cat >/tmp/service-file <<EOF
[Unit]
Description=$SERVICENAME
Requires=docker.service
After=docker.service

[Service]
Restart=no
User=$(whoami)
Group=docker
TimeoutStopSec=15
WorkingDirectory=$(pwd)
ExecStartPre=$(which docker-compose) down
ExecStart=$(which docker-compose) up
ExecStop=$(which docker-compose) down

[Install]
WantedBy=multi-user.target
EOF
sudo mv /tmp/service-file "/etc/systemd/system/$SERVICENAME.service"

echo "Enabling & starting $SERVICENAME"
sudo systemctl enable $SERVICENAME.service
sudo systemctl start $SERVICENAME.service
